---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[remote_or_s3_file::default]
      - recipe[remote_or_s3_file_test::default]
    attributes:
      aws:
        aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
        aws_session_token: <%= ENV['AWS_SESSION_TOKEN'] %>
        region: 'us-east-1'
